import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "../providers"
import { Card } from "@/components/ui/card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderWrapper>
          <div className="flex justify-center items-center min-h-screen bg-gray-100">
            <Card className="w-[380px] h-[600px] bg-white shadow-xl rounded-2xl flex flex-col overflow-hidden py-0 gap-0">
              {/* Header */}
              <div className="bg-emerald-600 text-white px-4 py-5 font-semibold text-center  rounded-tl-2xl  rounded-tr-2xl">
                Chat App
              </div>
              <div className="overflow-y-auto  ">
                 {children}
              </div>
             
            </Card>
          </div>

        </ProviderWrapper>

      </body>
    </html>
  );
}
